# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Bring' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'KakaoSDKAuth'	
  pod 'KakaoSDKUser'	
  pod 'KakaoSDKCommon'

  pod 'youtube-ios-player-helper'
  pod 'Alamofire', '~> 5.2'
  # Pods for Bring

end
